### ISSUE TITLE
ERROR: Error: self signed certificate

### ISSUE THREAD

**Issue by l0rraine** [antfu/vscode-iconify#11]
🈶 Activated, v0.2.2
🎛 108 icon sets loaded
☁️ [mdi] Downloading from https://raw.githubusercontent.com/iconify/collections-json/master/json//mdi.json
🐛 ERROR: Error: self signed certificate
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
