### ISSUE TITLE
不支持yml

### ISSUE THREAD

**Issue by xiaoxian521** [antfu/vscode-iconify#21]
use https://github.com/antfu/vitesse
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/44761321/157823082-b87939f6-8e96-4b0d-9498-0f8088553b25.png">

**Comment by xiaoxian521** [comment]
所以就是不支持？

**Comment by antfu** [comment]
学习一下怎么问问题

**Comment by xiaoxian521** [comment]
你好厉害啊
