### ISSUE TITLE
"-" Delimiter not working properly

### ISSUE THREAD

**Issue by niklaskdk** [antfu/vscode-iconify#24]
Using the - delimiter shows an already filtered list of icons:

![image](https://user-images.githubusercontent.com/7809265/166872995-4583ed35-0322-4a64-aebb-67077fa44e69.png)

Using either of the other default ones (: or /) shows the entire list

![image](https://user-images.githubusercontent.com/7809265/166873121-a78da42b-405c-4f70-89ab-4d0637c0b949.png)

**Comment by JohnCampionJr** [comment]
I took a stab at fixing this and failed spectacularly.  As fas as I can tell, "carbon-" and "carbon:" returns the same list of suggestions to VS Code, but VS Code declines to show them with the dash.

**Comment by jd-solanki** [comment]
> VS Code declines to show them with the dash

Is this from VS Code, then?

**Comment by alokVishu** [comment]
+1

**Comment by ThaDaVos** [comment]
> > VS Code declines to show them with the dash
> 
> Is this from VS Code, then?

Don't think so - as I used a different extension prior to this, which used the `-` and worked - so maybe a difference in implementation?

**Comment by Sight-wcg** [comment]
related: https://github.com/microsoft/vscode/issues/135861#issuecomment-952037304

**Comment by kieuminhcanh** [comment]
lỗi này vẫn chưa được sửa.
