### ISSUE TITLE
Does not work with Nuxt Icon module

### ISSUE THREAD

**Issue by ojvribeiro** [antfu/vscode-iconify#37]
### Describe the bug

Icon does not show if using in a Nuxt (3) project using the [Nuxt Icon module](https://github.com/nuxt-modules/icon). Worked great in other frameworks though.

![image](https://user-images.githubusercontent.com/8026741/208268277-645a0243-b81e-49b3-9f28-0cb1bb75d9fe.png)

### Reproduction

Use the extension in a Nuxt 3 project using the Nuxt Icon module

### System Info

```Shell
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
  Memory: 5.77 GB / 15.91 GB

Binaries:
  Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
  npm: 6.14.9 - ~\AppData\Roaming\npm\npm.CMD

Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
  Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KnifeFed** [comment]
This is still an issue. The preview doesn't work with HeroIcons v1 Solid/Outline.
