### ISSUE TITLE
Webstorm please!

### ISSUE THREAD

**Issue by adoin** [antfu/vscode-iconify#38]
### Clear and concise description of the problem

It will be awesome if there is a webstorm iconify plugin.

### Suggested solution

It will be awesome if there is a webstorm iconify plugin.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This is out of scope. Thanks.
