### ISSUE TITLE
会错误的显示elementui的 el-link组件

### ISSUE THREAD

**Issue by pandavips** [antfu/vscode-iconify#41]
### Describe the bug

会错误的显示elementui的 el-link组件

### Reproduction

none

### System Info

```Shell
win10 

版本: 1.75.1 (system setup)
提交: 441438abd1ac652551dbe4d408dfcec8a499b8bf
日期: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuiqg** [comment]
刚发现就看到这条反馈
![image](https://user-images.githubusercontent.com/2096890/232533145-2341fea0-e88a-45c6-95fb-158410559ee4.png)

**Comment by antfu** [comment]
You can set `"iconify.includes": ["el"]` in your config.
