### ISSUE TITLE
How is the custom icon displayed?

### ISSUE THREAD

**Issue by waset** [antfu/vscode-iconify#47]
### Additional context

``` ts
// uno.config.ts
import { defineConfig } from 'unocss'

// loader helpers
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'

export default defineConfig({
  presets: [
    presetIcons({
      collections: {
        // a helper to load icons from the file system
        // files under `./assets/icons` with `.svg` extension will be loaded as it's file name
        // you can also provide a transform callback to change each icon (optional)
        'my-icons': FileSystemIconLoader(
          './assets/icons',
          svg => svg.replace(/#fff/, 'currentColor')
        )
      }
    })
  ]
})
```
How can the above custom configuration be displayed in the editor through this plug-in?

**Comment by antfu** [comment]
Duplicated #12

**Comment by waset** [comment]
@antfu oh no, sorry, i mean, let the plug-in display icons in vscode.

Pass through `FileSystemIconLoader` 

<img width="1019" alt="image" src="https://github.com/antfu/vscode-iconify/assets/55943270/c9da92ff-b348-4ea1-9ab0-78a8daaa1937">

**Comment by s3xysteak** [comment]
Hope [unplugin-iconify-generator](https://github.com/s3xysteak/unplugin-iconify-generator) could help you!
