### ISSUE TITLE
Storing cache in globalState is causing slow startup

### ISSUE THREAD

**Issue by Legend-Master** [antfu/vscode-iconify#48]
### Describe the bug

We're storing icon cache in `globalState`, and it will be saved to `globalStorage/state.vscdb` which gets loaded in every startup even after uninstall

I discovered this when trying to troubleshoot why my vscode is starting slowly recently, and found something related in loading storage in `perfview.show`, and saw this big cache entry in it, removing it solves the problem

### Reproduction

Try use some icons and use `perfview.show` to see `code/didInitStorage`'s delta time

### System Info

```Shell
* Code: 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06)
* OS: win32(10.0.19045)
* CPUs: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz(12 x 2592)
* Memory(System): 15.83 GB(6.97GB free)

- 1TB M.2 SSD
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
PR welcome if you have better solutions. Thanks

**Comment by Legend-Master** [comment]
I'll take a look, maybe using the way how built-in json language features extension store schema caches
