### ISSUE TITLE
NuxtLabs UI syntax support

### ISSUE THREAD

**Issue by ddahan** [antfu/vscode-iconify#51]
### Clear and concise description of the problem

NuxtLabsUI built-in icon system use a different syntax to define an icon, for example:

```
<UButton icon="i-heroicons-magnifying-glass" />
```

Currently, it is displayed like this in VS Code using this extension:

<img width="179" alt="image" src="https://github.com/antfu/vscode-iconify/assets/1933516/103ad04e-f8fd-4428-bbd3-e0d4c0e943a9">

### Suggested solution

I suggest to be able to recognize this alternative syntax to have the expected result:

<img width="162" alt="image" src="https://github.com/antfu/vscode-iconify/assets/1933516/d5ba1416-d82b-4ade-8711-429da9561422">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Well, I am not very sure about this. I created this extension, as well as the. `i-` prefix. To me I think it's fine to display as `i-🔍` to be explicit about the existence of the prefix. On the other hand, in the icons preset of UnoCSS you can pass an empty string as the prefix to have `collect:icon` like convention. Thanks for bringing this up.
