### ISSUE TITLE
Matching expressions in the import statements are changed to icons

### ISSUE THREAD

**Issue by DamianGlowala** [antfu/vscode-iconify#52]
### Describe the bug

Before extension is loaded:
![image](https://github.com/antfu/vscode-iconify/assets/48835293/e47cfb7d-d9cc-49ac-b22d-50825b7dd473)

After extension is loaded:
![image](https://github.com/antfu/vscode-iconify/assets/48835293/5799cb26-616f-4244-ac95-cfd769441ba0)

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Fixed in 124d5174a7e2e2d802ab34a93e0e6ad5b37dc48c
