### ISSUE TITLE
jsdelivr Cdn entry not working

### ISSUE THREAD

**Issue by renatomoor** [antfu/vscode-iconify#54]
### Describe the bug

When visiting https://cdn.jsdelivr.net/gh/iconify/icon-sets/json
I have the error:
Package size exceeded the configured limit of 50 MB. Try https://github.com/iconify/icon-sets/tree/2.2.97/json instead.

I think this might be the reason I do not have autocomplete

### Reproduction

Go to https://cdn.jsdelivr.net/gh/iconify/icon-sets/json

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 740.41 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.5.1 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 113.0.1774.57
    Safari: 16.5.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mblouka** [comment]
I also have this issue. It's probably an issue with the icon-set package.

**Comment by renatomoor** [comment]
@antfu I've tried with the new CDN https://icones.js.org/collections but the page returns a Not found

**Comment by mblouka** [comment]
> @antfu I've tried with the new CDN https://icones.js.org/collections but the page returns a Not found

`/collections` index isn't meant to return anything. Try `/collections/fluent.json` in your browser, you'll see it loads the icons as intended.
