### ISSUE TITLE
Using `/` as separator between collection and icon name no longer works by default

### ISSUE THREAD

**Issue by Legend-Master** [antfu/vscode-iconify#57]
### Describe the bug

After 124d5174a7e2e2d802ab34a93e0e6ad5b37dc48c, using `/` as separator between collection and icon name (e.g. https://github.com/antfu/unplugin-icons#usage) no longer works by default (can be configured in settings though)

> ```ts
> import IconAccessibility from '~icons/carbon/accessibility'
> import IconAccountBox from '~icons/mdi/account-box'
> ```

Since you removed it explicitly, is this syntax considered bad or something?

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Oh, it was removed for a false positive in the import path. I forgot about this usage, added it back.
