### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by RebeccaStevens** [antfu/vscode-iconify#58]
### Clear and concise description of the problem

Icons aren't shown for aliased icon names. It would be great if they could be.

### Suggested solution

Ability to read a json file like this to get the aliases.

```jsonc
{
  aliases: {
    "chevron-left": "ri:arrow-left-s-line",
    "chevron-up": "ri:arrow-up-s-line",
    "chevron-right": "ri:arrow-right-s-line",
    "chevron-down": "ri:arrow-down-s-line",
    // ...
  }
}
```

### Additional context

I'm using [nuxt icon](https://github.com/nuxt-modules/icon) which allows for declaring aliases for icons. [Config details](https://github.com/nuxt-modules/icon#configuration-%EF%B8%8F)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by arthur-leclerc** [comment]
Hi, I would add that it would be nice to be able to also put an alias on an entire collection.

For example, `simple-icons` is defined with the alias `si` [on a project](https://gethomepage.dev/v0.8.2/configs/services/#icons) I use.

**Comment by antfu** [comment]
Sure, PR welcome :)

**Comment by RebeccaStevens** [comment]
@arthur-leclerc There's already an option for that: https://github.com/antfu/vscode-iconify/blob/d295384d5f642791f52d36432b58369e4fac1603/package.json#L526-L530

**Comment by lumosminima** [comment]
@RebeccaStevens How is this supposed to be used? I have:
```JS
// settings.json
...
 "iconify.customCollectionIdsMap": {
    "ms": "material-symbols",
    "logo": "logos",
    "spinners": "svg-spinners",
  },
  "iconify.customCollectionJsonPaths": [
    "./.vscode/iconsMap.json"
  ],
...
```
And:
```JS
// iconsMap.json

{
    "i-add": "i-ms-add",
    "i-check": "i-ms-check-small",
    "i-avatar": "i-ms-account-circle-outline",
    "i-delete": "i-ms-delete-outline",
    "i-signout": "i-ms-logout",
}
```
I have same mapping as above inside another `iconShortcuts.ts` to actually match the aliases but they don't display any icon also `customCollectionIdsMap` stops working whereas previously `i-ms-check` would display a `✔️`. If I remove `customCollectionJsonPaths` then it starts working again. So docs on proper usage would be awesome!

**Comment by RebeccaStevens** [comment]
@lumosminima You'll want to use `customAliasesJsonPaths` instead of `customCollectionJsonPaths`. `customCollectionJsonPaths` is for providing your own custom icon set.

**Comment by lumosminima** [comment]
@RebeccaStevens 🤦‍♂️ got it! though for some reason they only work if I don't have the `i-` prefix in both shortcuts and map so `icon-check` works but not `i-check`. Thanks for this eye candy 🤩
