### ISSUE TITLE
Avoid jumping left and right on focusing on/leaving current line

### ISSUE THREAD

**Issue by shrekuu** [antfu/vscode-iconify#69]
### Clear and concise description of the problem

I have code like this: `<Icon icon="mdi:heart-outline" className="h-5 w-5" />`

The icon name shows when I put the cursor on this line, disappears when I move cursor to other lines. The icon image disappears when the name fails to match one icon.  The code jumps left and right.

### Expected result
I think it would be great of the code does not jump left and right, at least not that much distance when we focus on or leave this line.

### Suggested solution

When this plugin is enabled, just keep some space(may be some sign/graph to indicate that no icon matches the icon name) before the icon name literal to show the icon.  Or at least always show the icon name, so the line does not shift left and right that much distance when we focus on or leave this line. Maybe adding something we can configure in the settings? Sorry I am not capable of creating a PR.

<img width="383" alt="image" src="https://github.com/antfu/vscode-iconify/assets/3136026/d532fc69-8a04-4bf4-a4e4-28b5b71253e3">

Thanks Anthony Fu. ❤️

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by s3xysteak** [comment]
Disable the option `iconify.inplace` may be helpful.

**Comment by shrekuu** [comment]
@s3xysteak Cool! Thanks. I never knew this feature. The code is tamed.

<img width="392" alt="image" src="https://github.com/user-attachments/assets/ad7b7731-0baa-469d-8125-770eb8888d4a">
