### ISSUE TITLE
can add proxy config?

### ISSUE THREAD

**Issue by Lanseria** [antfu/vscode-iconify#7]
```
[ant-design] Downloading from https://raw.githubusercontent.com/iconify/collections-json/master/json//ant-design.json
🐛 ERROR: Error: getaddrinfo ENOENT raw.githubusercontent.com
Error: getaddrinfo ENOENT raw.githubusercontent.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

**Comment by antfu** [comment]
Guess maybe it's better to use a global proxy or whitelist your VS Code.

**Comment by wuyiw** [comment]
FYI: it seems that `axios`(use by `vscode-iconify`) can't get https content via http proxy: axios/axios#658 and to make it work with socks5 proxy some extra work is needed: axios/axios#636.

**Comment by mseele** [comment]
After having proxy issues, I've investigated a little bit:
Seems that `axios` uses the http_proxy / https_proxy env variables (https://github.com/axios/axios/pull/366) but, like @wuyiw mentioned, it is not possible to get https content via a http proxy (https://github.com/axios/axios/issues/658) which is quite common in bigger networks.
I can't believe that there is no js http client out there that makes things right!?! If somebody knows of a js http client library that handles proxies correct, i would love to create a pr to make the plugin work for all people behind proxies.
