### ISSUE TITLE
[Error] Does not work behind proxy

### ISSUE THREAD

**Issue by mubaidr** [antfu/vscode-iconify#74]
### Describe the bug

When using proxy setting in vscode, icon set failed to load with following error: 

```bash
🈶 Activated, v0.7.5
🎛 167 icon sets loaded
⏳ [heroicons] Downloading from https://icones.js.org/collections/heroicons.json
🐛 ERROR: FetchError: [GET] "https://icones.js.org/collections/heroicons.json": <no response> fetch failed
FetchError: [GET] "https://icones.js.org/collections/heroicons.json": <no response> fetch failed
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetchRaw2 (c:\Users\ubaid58653\.vscode-insiders\extensions\antfu.iconify-0.7.5\index.js:10597:14)
    at $fetch22 (c:\Users\ubaid58653\.vscode-insiders\extensions\antfu.iconify-0.7.5\index.js:10630:16)
    at c:\Users\ubaid58653\.vscode-insiders\extensions\antfu.iconify-0.7.5\index.js:10741:16
```

Please note that: 
- all other vscode features (updates, extensions) work fine
- I have followed this thread: https://github.com/antfu/vscode-iconify/issues/7
- I have tried setting `http.proxySupport` to "on" & "override"
- I can access the icon json link in browser (https://icones.js.org/collections/heroicons.json)

### Reproduction

Just set proxy with auth i.e. http://12345:12345@127.0.0.1:1234

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 15.66 GB / 31.73 GB
  Binaries:
    Node: 20.12.0 - E:\dev_tools\nodejs\node.EXE
    npm: 10.5.0 - E:\dev_tools\nodejs\npm.CMD
    pnpm: 8.15.5 - E:\dev_tools\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (123.0.2420.65)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mmach2000** [comment]
My workaround: download all icon-set JSONs; setup a local server using miniserve, etc.

**Comment by kathirr007** [comment]
> Enabling `http.experimental.systemCertificatesV2` worked for me.

This works for me. Thank you @Ahuahuachi
