### ISSUE TITLE
icon not show for Hugeicons

### ISSUE THREAD

**Issue by sdnteja2** [antfu/vscode-iconify#82]
### Describe the bug

<img width="618" alt="image" src="https://github.com/user-attachments/assets/ce7b2cb6-f951-4244-95d1-9eed96b587cf">

### Reproduction

Development

### System Info

```Shell
System:
    OS: macOS 13.6.7 
  Binaries:
    Node: 20.15.0 
    bun: 1.1.17  
  Browsers: 
    Edge: 126.0.2592.81
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
v0.9 should fix it
