### ISSUE TITLE
support config the exclude files patterns to disable preview

### ISSUE THREAD

**Issue by tjx666** [antfu/vscode-iconify#87]
### Clear and concise description of the problem

I generate the icon types in icons.d.ts which include many icons about 3500 icons.

When I open the file, vscode crash and no respond.

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/f8f16add-d22f-4d4d-b09e-906681823b14">

### Suggested solution

support config files to disable preview.

```json
{
    "iconify.preview.exclude": ["**/typings/icon.d.ts"]
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, pr welcome!
