### ISSUE TITLE
Option to show icon with text simultaneously

### ISSUE THREAD

**Issue by robokozo** [antfu/vscode-iconify#94]
### Clear and concise description of the problem

When adding a attributes to an icon, I dont like that the text expands. Sometimes its a little confusing and moves in ways I didn't expect

### Suggested solution

The text icon and text should be shown at the same time. Similar to when the cursor is inside the text

```
<🍔i-icon:hamburger />
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
```json
"iconify.inplace": false
```
